### ISSUE TITLE
Delete image not working

### ISSUE THREAD

**Issue by SBillion** [Streetwise-Media/Froala-Image-Caption#2]
When using image_caption.js with Froala 1.5, the delete method is impossible to use:
  
TypeError: b is undefined

**Comment by mrdziuban** [comment]
Do you mean Froala 1.2.5? I don't see Froala 1.5 in the [changelog](https://editor.froala.com/changelog).

**Comment by SBillion** [comment]
Yes I mean 1.2.5. Sorry for that

**Comment by mrdziuban** [comment]
@SBillion Thanks for catching this, it's fixed in latest commits. Let me know if that resolves your issue!
