### ISSUE TITLE
Can't move images

### ISSUE THREAD

**Issue by SBillion** [Streetwise-Media/Froala-Image-Caption#4]
Hi,

If the plugin is activated, I can't move images anymore.

**Comment by mrdziuban** [comment]
I just pushed a few commits that should resolve this issue for you. In the future, please make sure to include relevant information about your Froala setup, including version number, so I can more easily test the issue. Let me know if you still have issues after trying the latest version of the plugin.

**Comment by SBillion** [comment]
Yes sorry, you're right, I didn't send you enough information. I use last froala release version, 1.2.5
I'll try your commits tonight.
Thank you for that
